# Generated by Django 5.0.4 on 2024-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0003_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
    ]
