# Generated by Django 5.0.4 on 2024-04-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0005_remove_roster_players_roster_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='player',
            new_name='players',
        ),
    ]
